apiVersion: 1
datasources:
  - name: Monitoring Postgres
    type: postgres
    access: proxy
    url: monitoring-postgres:5432
    database: monitoring
    user: monitor
    secureJsonData:
      password: monitor
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
