global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "mlops_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "otel_collector"
    static_configs:
      - targets: ["otel-collector:8888"]
